####THIS PROGRAM USES EXCEPTION BASICALLY IT PREPARES FOR AND ERROR SUPPORSE THERE
##IS A PROGRAM THAT HAS NO FILE INSTEAD OF SYNTAX ERROR IT GIVES
#THE FILE COULDNT BE FOUND OUTPUT



def to_celsius(temp):






    except FileNotFoundError:
    PRINT("File not found")


